title: "Mi primer post"
date: 2019-02-12
title: Pages with jekyll
author: paulocolorado
email: superpaco23@gmail.com
description: > # this means to ignore newlines until "baseurl:"
H

# social links
twitter_username: @PauloEmilioCol
github_username:  @paulocolorado

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
